[package]
name = "wwvb_audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.20.1"

[profile.release]
opt-level = 3
debug = true
lto = true
panic = "unwind"
codegen-units = 1